name: Build Capacitor App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
            artifact_path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
            artifact_name: app-android.apk
          - platform: ios
            os: macos-latest
            artifact_path: frontend/ios/build/Build/Products/Debug-iphonesimulator/App.app # Path inside derivedDataPath
            artifact_name: app-ios.app
          - platform: electron
            os: windows-latest
            artifact_path: frontend/electron/dist
            artifact_name: electron-app
      fail-fast: false  # Continue with other platforms if one fails

    steps:
    - uses: actions/checkout@v3

    # Set up Python for backend
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Set up Node.js for frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend

    # Update package.json to fix dependency issues - Linux version (Adjusted sed for compatibility)
    - name: Fix package.json (Linux/macOS)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        # Use different sed args based on OS
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          sed -i '' 's/"@capacitor\/storage": "\^5.0.6"/"@capacitor\/preferences": "\^5.0.6"/g' package.json
          sed -i '' 's/import { Storage } from '"'"'@capacitor\/storage'"'"'/import { Preferences } from '"'"'@capacitor\/preferences'"'"'/g' src/js/app.js
          sed -i '' 's/Storage\./Preferences\./g' src/js/app.js
        else # Linux
          sed -i 's/"@capacitor\/storage": "\^5.0.6"/"@capacitor\/preferences": "\^5.0.6"/g' package.json
          sed -i 's/import { Storage } from '"'"'@capacitor\/storage'"'"'/import { Preferences } from '"'"'@capacitor\/preferences'"'"'/g' src/js/app.js
          sed -i 's/Storage\./Preferences\./g' src/js/app.js
        fi
      shell: bash
      working-directory: frontend

    # Update package.json to fix dependency issues - Windows version
    - name: Fix package.json (Windows)
      if: matrix.platform == 'electron' # Only run on the electron job
      run: |
        (Get-Content package.json) -replace '"@capacitor/storage": "\^5.0.6"', '"@capacitor/preferences": "^5.0.6"' | Set-Content package.json
        (Get-Content src/js/app.js) -replace 'import { Storage } from ''@capacitor/storage''', 'import { Preferences } from ''@capacitor/preferences''' | Set-Content src/js/app.js
        (Get-Content src/js/app.js) -replace 'Storage\.', 'Preferences.' | Set-Content src/js/app.js
      shell: pwsh
      working-directory: frontend

    # Install Node.js dependencies
    - name: Install Node.js dependencies
      run: |
        npm install
        # Install TypeScript as a dev dependency (required by Capacitor)
        npm install -D typescript
        # Install Electron for Windows builds
        if ("${{ matrix.platform }}" -eq "electron") {
          npm install -D @capacitor/electron electron electron-builder
        }
      shell: pwsh # Use PowerShell for consistency on Windows
      working-directory: frontend

    # Build the frontend
    - name: Build frontend
      run: |
        npm run build
      working-directory: frontend

    # Android-specific steps
    - name: Set up JDK (Android only)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
      if: matrix.platform == 'android'

    # iOS-specific steps
    - name: Install Cocoapods (iOS only)
      run: |
        sudo gem install cocoapods
      if: matrix.platform == 'ios'

    # Add platform
    - name: Add platform
      run: |
        npx cap add ${{ matrix.platform }}
      working-directory: frontend
      shell: pwsh # Use PowerShell on Windows

    # Sync assets
    - name: Sync Capacitor
      run: |
        npx cap sync ${{ matrix.platform }}
      working-directory: frontend
      shell: pwsh # Use PowerShell on Windows

    # --- Debug Step 1: List Frontend Directory Contents ---
    - name: List Frontend Directory Contents (Windows)
      if: matrix.platform == 'electron'
      run: |
        Write-Host "--- Recursive listing of D:\a\torn-browser-app\torn-browser-app\frontend ---"
        Get-ChildItem -Path frontend -Recurse -ErrorAction SilentlyContinue | Format-Table -AutoSize | Out-String -Width 4096
        Write-Host "--- End of recursive listing ---"
      shell: pwsh

    # --- Debug Step 2: Check Electron Directory Exists ---
    - name: Check Electron Directory Exists (Windows)
      if: matrix.platform == 'electron'
      run: |
        Write-Host "Checking existence of D:\a\torn-browser-app\torn-browser-app\frontend\electron"
        Test-Path -Path frontend\electron # Check if frontend\electron exists
      shell: pwsh

    # Build for Android
    - name: Build Android APK
      if: matrix.platform == 'android'
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug
      working-directory: frontend/android

    # Build for iOS
    - name: Build iOS app
      if: matrix.platform == 'ios'
      run: |
        # Install pods specifying the project directory containing the Podfile
        pod install --project-directory=App --repo-update
        # Build from the ios directory
        xcodebuild -workspace App/App.xcworkspace -scheme App -configuration Debug -sdk iphonesimulator -derivedDataPath build build
      working-directory: frontend/ios

    # Build for Electron (Windows)
    - name: Build Electron app
      if: matrix.platform == 'electron'
      run: |
        npm run electron:build
      working-directory: frontend\electron # Keep using backslash, will work if directory exists
      shell: pwsh

    # Upload platform-specific artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_path }}
