name: Build Capacitor App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
            artifact_path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
            os_suffix: apk # Or keep specific like 'android' if preferred
            artifact_name: app-android.${{ matrix.os_suffix }}
          - platform: ios
            os: macos-latest
            artifact_path: frontend/ios/App/build/Build/Products/Debug-iphonesimulator/App.app
            os_suffix: app # Or keep specific like 'ios' if preferred
            artifact_name: app-ios.${{ matrix.os_suffix }}
          - platform: electron
            os: windows-latest
            artifact_path: frontend/electron/dist_electron
            os_suffix: windows # Define the suffix here
            artifact_name: electron-app-${{ matrix.os_suffix }} # Use the defined suffix
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json' # More robust path

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend

    - name: Fix package.json and app.js (Windows)
      if: matrix.platform == 'electron'
      run: |
        (Get-Content package.json) -replace '"@capacitor/storage": "\^5.0.6"', '"@capacitor/preferences": "^5.0.6"' | Set-Content package.json
        (Get-Content src/js/app.js) -replace 'import { Storage } from ''@capacitor/storage''', 'import { Preferences } from ''@capacitor/preferences''' | Set-Content src/js/app.js
        (Get-Content src/js/app.js) -replace 'Storage\.', 'Preferences.' | Set-Content src/js/app.js
      shell: pwsh
      working-directory: frontend

    - name: Fix package.json and app.js (Linux/macOS)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          sed -i '' 's/"@capacitor\/storage": "\^5.0.6"/"@capacitor\/preferences": "\^5.0.6"/g' package.json
          sed -i '' 's/import { Storage } from '"'"'@capacitor\/storage'"'"'/import { Preferences } from '"'"'@capacitor\/preferences'"'"'/g' src/js/app.js
          sed -i '' 's/Storage\./Preferences\./g' src/js/app.js
        else
          sed -i 's/"@capacitor\/storage": "\^5.0.6"/"@capacitor\/preferences": "\^5.0.6"/g' package.json
          sed -i 's/import { Storage } from '"'"'@capacitor\/storage'"'"'/import { Preferences } from '"'"'@capacitor\/preferences'"'"'/g' src/js/app.js
          sed -i 's/Storage\./Preferences\./g' src/js/app.js
        fi
      shell: bash
      working-directory: frontend

    - name: Install Node.js dependencies
      run: npm install
      working-directory: frontend

    - name: Install TypeScript
      run: npm install -D typescript
      working-directory: frontend

    - name: Install Electron dependencies
      if: matrix.platform == 'electron'
      run: npm install -D @capacitor/electron electron electron-builder
      working-directory: frontend

    - name: Build frontend (web assets)
      run: npm run build
      working-directory: frontend

    - name: Set up JDK (Android only)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
      if: matrix.platform == 'android'

    - name: Install Cocoapods (iOS only)
      run: sudo gem install cocoapods
      if: matrix.platform == 'ios'

    - name: Add Capacitor platform ${{ matrix.platform }}
      run: npx cap add ${{ matrix.platform }} --npm
      working-directory: frontend

    - name: Sync Capacitor assets
      run: npx cap sync ${{ matrix.platform }}
      working-directory: frontend

    - name: Build Android APK
      if: matrix.platform == 'android'
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon
      working-directory: frontend/android

    - name: Build iOS app
      if: matrix.platform == 'ios'
      run: |
        pod install --project-directory=App --repo-update
        xcodebuild -workspace App/App.xcworkspace -scheme App -configuration Debug -sdk iphonesimulator build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      working-directory: frontend/ios

    - name: Build Electron app
      if: matrix.platform == 'electron'
      run: npm run electron:build
      working-directory: frontend
      shell: pwsh

    - name: Upload artifact (${{ matrix.artifact_name }})
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_path }}
        if-no-files-found: error
