name: Build Capacitor App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
            artifact_path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
            artifact_name: app-android.apk
          - platform: ios
            os: macos-latest
            # Using original path, double-check if this is correct for your final build output
            artifact_path: frontend/ios/build/Build/Products/Debug-iphonesimulator/App.app
            artifact_name: app-ios.app
          - platform: electron
            os: windows-latest
            artifact_path: frontend/electron/dist # This is the output of electron-builder
            artifact_name: electron-app
      fail-fast: false

    steps:
    - uses: actions/checkout@v3 # Reverted to v3

    - name: Set up Python
      uses: actions/setup-python@v4 # Reverted to v4
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v3 # Reverted to v3
      with:
        node-version: '18'
        cache: 'npm' # Keep npm caching
        cache-dependency-path: frontend/package.json

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend

    - name: Fix package.json (Linux/macOS)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          sed -i '' 's/"@capacitor\/storage": "\^5.0.6"/"@capacitor\/preferences": "\^5.0.6"/g' package.json
          sed -i '' 's/import { Storage } from '"'"'@capacitor\/storage'"'"'/import { Preferences } from '"'"'@capacitor\/preferences'"'"'/g' src/js/app.js
          sed -i '' 's/Storage\./Preferences\./g' src/js/app.js
        else
          sed -i 's/"@capacitor\/storage": "\^5.0.6"/"@capacitor\/preferences": "\^5.0.6"/g' package.json
          sed -i 's/import { Storage } from '"'"'@capacitor\/storage'"'"'/import { Preferences } from '"'"'@capacitor\/preferences'"'"'/g' src/js/app.js
          sed -i 's/Storage\./Preferences\./g' src/js/app.js
        fi
      shell: bash
      working-directory: frontend

    - name: Fix package.json (Windows)
      if: matrix.platform == 'electron'
      run: |
        (Get-Content package.json -Raw) -replace '"@capacitor/storage": "\^5.0.6"', '"@capacitor/preferences": "^5.0.6"' | Set-Content package.json -NoNewline
        (Get-Content src/js/app.js -Raw) -replace 'import { Storage } from ''@capacitor/storage''', 'import { Preferences } from ''@capacitor/preferences''' | Set-Content src/js/app.js -NoNewline
        (Get-Content src/js/app.js -Raw) -replace 'Storage\.', 'Preferences.' | Set-Content src/js/app.js -NoNewline
      shell: pwsh
      working-directory: frontend

    - name: Install Node.js dependencies
      run: |
        npm ci # Use ci for faster, reliable installs in CI
        npm install -D typescript
        if ("${{ matrix.platform }}" -eq "electron") {
          # Ensure these are installed as devDependencies in the main frontend package.json
          # Using specific known-good versions for Capacitor 5/Electron 28
          npm install -D @capacitor/electron@^5.0.0 electron@^28.0.0 electron-builder@^24.0.0
        }
      shell: pwsh
      working-directory: frontend

    - name: Build frontend (web assets)
      run: npm run build
      working-directory: frontend
      env:
        CI: true # Often needed for build scripts

    - name: Set up JDK (Android only)
      if: matrix.platform == 'android'
      uses: actions/setup-java@v3 # Reverted to v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Cocoapods (iOS only)
      if: matrix.platform == 'ios'
      run: sudo gem install cocoapods

    # --- Capacitor Syncing ---
    # Run add and sync sequentially, checking for errors.
    - name: Add Capacitor platform ${{ matrix.platform }}
      run: |
        npx cap add ${{ matrix.platform }}
        if ($LASTEXITCODE -ne 0) { throw "npx cap add ${{ matrix.platform }} failed" }
      working-directory: frontend
      shell: pwsh

    - name: Sync Capacitor assets
      run: |
        npx cap sync ${{ matrix.platform }}
        if ($LASTEXITCODE -ne 0) { throw "npx cap sync ${{ matrix.platform }} failed" }
      working-directory: frontend
      shell: pwsh

    # --- Platform Builds ---
    - name: Build Android APK
      if: matrix.platform == 'android'
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon # Add --no-daemon for CI environments
      working-directory: frontend/android

    - name: Build iOS app
      if: matrix.platform == 'ios'
      run: |
        pod install --repo-update # Run pod install relative to working-directory
        xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -sdk iphonesimulator -derivedDataPath ../build build # Keep relative path for build output
      working-directory: frontend/ios/App # Run xcodebuild from where the workspace is

    # *** List contents AFTER sync to verify electron dir ***
    - name: List Directory Contents After Sync (Electron only)
      if: matrix.platform == 'electron'
      run: |
        Write-Host "--- Listing ./frontend ---"
        Get-ChildItem -Path ./frontend -ErrorAction SilentlyContinue | Format-Table -AutoSize | Out-String -Width 4096
        Write-Host "--- Listing ./frontend/electron ---"
        Get-ChildItem -Path ./frontend/electron -Recurse -ErrorAction SilentlyContinue | Format-Table -AutoSize | Out-String -Width 4096
      shell: pwsh
      working-directory: . # Run from checkout root to see full paths

    - name: Build Electron app
      if: matrix.platform == 'electron'
      # Run electron-builder from the electron project directory
      # Ensure package.json inside frontend/electron exists and is set up
      # Or configure electron-builder via frontend/package.json 'build' section
      run: |
        npx electron-builder build --win --config.asarUnpack=node_modules/@capacitor/electron/**/*
        if ($LASTEXITCODE -ne 0) { throw "npx electron-builder failed" }
      working-directory: frontend/electron # <--- Correct directory for electron-builder
      shell: pwsh

    - name: Upload artifact (${{ matrix.artifact_name }})
      uses: actions/upload-artifact@v4 # Keep v4 as it's the current stable
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_path }}
        if-no-files-found: error
